version: 2
updates:
  - package-ecosystem: "npm"
    directory: /
    schedule:
      interval: "daily"
      time: "05:00"
      timezone: "America/Los_Angeles"
  - package-ecosystem: "github-actions"
    directory: /.github/workflows
    schedule:
      interval: "daily"
      time: "05:00"
      timezone: "America/Los_Angeles"
